# webforJ configuration file (HOCON format).
# See: https://docs.webforj.com/docs/configuration/properties

webforj.entry = com.webforj.databinding.Application
webforj.debug = true
webforj.reloadOnServerError = on
